HOST: 127.0.0.1
PORT: 8080

SWAGGER_FILE_PATH: swagger/swagger.yaml
LOGGER_CONFIG_PATH: configs/logger.conf

REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_DB: 0

SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:secret@localhost:5433/test?application_name=access_control_service

USER_MANAGEMENT_URL: http://127.0.0.1:8081/v1
USER_MANAGEMENT_API_KEY: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5MzAyODUxOCwianRpIjoiMmY5NTY2NjctODc1Mi00YmE3LWFlODUtYjRmYTNiNjA5NzEyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFjY2Vzc19jb250cm9sX3NlcnZpY2UiLCJuYmYiOjE2OTMwMjg1MTgsImV4cCI6NDg0NjYyODUxOH0.AlNrXKpJNtUXsmWg_dK9EsDRf854z4OM9uSsxTplj12PPMWd7kp1eQtXvOzTJFbrG9zaz8WayJyEBgOTEo77LdN1VWoHlhHSBG-q6OPTyr9L_pZq7AWagZOuqpBAk65jwu8zxDCfXgjtLOzHb3sbi8XC4JkMshmyuOOlCxZbqC8CU-twCtus222JHjAm8-RbFo5dFRq1HluFsrYNni-tFDAQATk12rEvCjuUTapy76HqdaJ4pCDpt8SvNO_1zp6Nus2kPC5vWRIm0K6upBtmQdp5dP-smE0ZbQfygpH7j2sXe5sA8v-GEbhlDYlmd_njRurPuqx-rfyWaAAnNvr03R6YWwnFZtpdDIP1EsaLd78f_e44dx7HmC2jxaUG7sDkNmm_QVR2eb_fxYfFv_7T1REX7jHhY7NYCeQm1gzZ7CZv0gVAs2xlR_7DX7PvfXWnDXpCrfU6afFntNOFZcjrip2ARjc-QG85WYQfH5B8wLimMmFbJt5NK0EZG1AgXrG18QXkbi5cpmCbtBcX5gX0tCNX90mQWRmMvNoXGQHAFdMKP1EXZ6eBPT0inwi9j4d2yJ1cKVcwiw9XnbCVi88aD19r503Q2o4HjjjTIq9HV4D9uuAfoqpXiRZHeG2bSwfcELyLmnNehml0T__MIDpw1LREzCyhAbkWP5iW-z_4H_A
NOTIFICATION_URL: http://127.0.0.1:8082/v1
NOTIFICATION_API_KEY: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5MzA2NjYzMiwianRpIjoiOTA1MmUwOWMtMjI1Yi00MTEwLThiMTAtYTM2YjMyZGJjODBhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im5vdGlmaWNhdGlvbl9zZXJ2aWNlIiwibmJmIjoxNjkzMDY2NjMyLCJleHAiOjQ4NDY2NjY2MzJ9.dNjPyx2AXA-rd9kmLL2EEyahUCrjKXmyM6-QSh5Cp384Feyfvbui2GkIYnim64-F93hkOj1VuMng2pjYb4SScaYc3860mVaaSfFsJcZ-wnlSA3ySnlgzCy3MCZRkeEV-bUGyi41p95B9UdtzoeERSjDkPZO-L-rgIc9qeYlT5UbsSKva9c8WuEdsr6rJe9rp-A4ZT6bWQ3WQiJcfDjnL1tQ5Jjyw7sdE5C_mO7_yrsFB56MiN-x1mX04dgGGvbknl4n-N_uO7iajXoJ-xoL1CKkVJyWSfl78NZTaHIxytGCI9PuDQYpiNSJ6kJ4f0cPq24H0j_4WGY_HRXux-ybF4H7RHahM7foWrZrp9O-PgmRTyvmDhZ6yikFUmMmDLUzZ8TBPW1OWDt4sONt3_vMuv1h3-aE1FDtz_sKL4oVcKGoNoiWSQmWzhrfAu7Qg9eDb-5j0tdnr6QScdd11sfuK5saWAoxwpARzVdjIf3lXQRMrbtd_hpocy551-NudErIMwm-h7YVStcSve6snEU75Dk5DPy8joi9MHsZS64Q9mArm6njDr7Lbc-lTqjArA2um9nH8djtAYH8siVOr-fygS0k4FQUwBGYp4_4qlRLPp4fgrW-81yJSfqwgl7HUMlHBtxpNEC64o6h3f7HaD10BftyD0KdZlks3fsLkLQGyY6g

SECRET_KEY: AnSSF1hXFta3CqXD0REXnQ

PRIVATE_KEY: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKwIBAAKCAgEAt+1ueXtNusxvaqgxRRRbNMyXFjPxI+zG6jyRW1CsBH0ZW1Ei
  jvoIx5eA/Noi8tdwiRFBkcPfhXHvZdaidYTwfWOtfUzIl+Sg/7BM1sQ9+YfqMhk3
  12D8lC/rLrPmrOQWVpWYz+z1B6bKfG1ZkAvkgo0c3I5SichyPYSM1Tl0onXEpbL4
  giHO5hok4VvPMQb2EfSq8UD+mxI2zTHFAP1PtOQcTWdeKC5k+ddfOEAAJayh3tEW
  uW2nMj2wunk7pVxnYparZFPw6vMNSiQ8rs2xmYnZQhuqZJgMRW/SxbDn/Zl6P1mB
  jKPNyVoAbu+/Fx41De66cnNXMdjC2LpQ+xrRWpFjoMJEU4KDq37/Ewk4Ee2gBKny
  uX23CZbZ/hPiSXczBD8fUJTdzHQUUHJB8YCCAZJnwvhA8Kf+cwI5vjxlVJeMguFq
  kXK53Cycxn6TXDEju5KiRTkyfAMwYpLnrUGi3zBO3mFClVA2EBaYTQf09WpKjg7D
  O0+08FH6FTRQHKimWBnTXb2RSme5YAmanY5CgiX9Qmn9DwulbUlSB5VujxqESgy1
  cDTNd7xMEcwWthMIcIojfsfDmuKT41nU6aGOI8lQN6CTEFZIbzKy6WDthiKLLogx
  LJxB7TTbpq7a0SNRKNv+l8Qpogjd24OKvCCYxWwbB9FRoYZpa/Q9n3DRpMUCAwEA
  AQKCAgEAoMQEQGMquhBfgtao2jzEzA3YMiwMpt4bsDpow2xsLzA5rbvpfRfH/M3M
  jTcOPT1avDQ9H/AZvEauflFxh08/9hneVxt6amoI3/V19HNryGSorEmmqbe4jr6j
  zxqoko57iAsSmwv/0URU0RWzp1j9z68QfyhXtN9kG6l0gBvMewR9cmhRF039ztsj
  SWg6Xhw7kc5ObLnm0hzFke3iyM6hkPeiVXX4sx56XHeIX15xwnx2sJAKUOIrtpp9
  k0DMhemS5HXWMce9WWBBSYELGa/pgM8g+8u60FqmvzrS/MF4xg4U8LKHriqvgUQO
  BOnCGa7pqNf2WHvAx200QsP4bMQwIIFYDkvq30dgMjrZmc3hg7Q5fKamhKf7A8sp
  7n+97pw2M2g/29/p6/ef/wuAdRoCIq80aY9MRK0/Z/yZL5SZJxCiMXflm15spxGH
  dNC/ojDv1ByVgzG/58E4G23ui/y89ubV0+zyH6ucRGzQl1beA6jzfqUwjoyw07An
  WOs0Is+4M1tWuA0cbfsFpY44Wcj8AbexrXxxmmgpSJBFQE9Lt40YQ5P+GPOzr07o
  wCf32jqt1po61PD3cJxMwvxLzuB3VznbAfS3FkwgLWdysDQmkNfJnHGjjE5fJ1DK
  3wrjU3nfkmBk2JLcOAcQH8hWaz8GnzAazYBNoqii8pUvPt62ZzECggEBAOrKgOVI
  22ttfoJFZmMfGJqD3Q5sbOoiPA9+0Hpgp99XHy+ds4kzcPeflT46y4b58OvPhAjy
  w2eFXFFN2zwrE4J8MkpghaDVSNsn+oTAg1YYgibaa9ee9oPG2DQr/SUCH19rvCI9
  VjIgVoVPoNB/xFT5u4ZqgnEWsGQaCkhZzZZL/4Ncdh/gfYkpyikhJND0sIqPE08K
  MOoBiya8qjleOB3nIIPChB5kx1DGYSwEHUI+1N2tDS/vBve9uoq1bYLwKvO4+88D
  Rfjkro4T6x7ePO+PoS13/MboMnvwjkOl9phW1BTPHWr7f5ZA+JNJiCCuRBeFUb4v
  ibl8DaAYW64O+/sCggEBAMiKt9gB8Zmi4yDjjfnnDrbaFOilDHZoyyQ6FR7AQfc5
  FVB9AD1aL0pHVSJnkWXF7iT2ji4BdCiXKw06IOWgAUsUM8zwZcn0te8XkFLBAwEc
  QVsmHAaOdLUO7MkMw6KstbeNzM4bhGDw2MqyUXszgSvzR6bvirVmNQ5p3FNsPqT5
  myjSl7rFwTwSM6G9WKDkKRMzhzAeJneSHIvhyAW5LqxRAhTx71ClRlncUgp8zi55
  e5qm5Ba6tFPQteFqVa9v8W2rIV0T+AqGKBwxM4iDkFo1ilYzacc/tmWJHl0S7sFO
  iwyeZKqQviG0wYIzfoSCvm+M8eQtXAErz/Jtkn7BRj8CggEBAJWFsOBTraiUamR7
  3eByBTEhmL1+vz2735PeptXIiB/rU6j3PUa6w85uipS+zK6ArbT+yo8ISvi6LTh5
  5IxEwn/up/hFz9PFAEjRBPFVyE4j/X7QyqzeRw9UqotPGD9hQql56q3DcgkqHu92
  7mrZcybKg2numnN6h4q4KqQ4zHxSmb4GPBPA2zFms5/Nw6xup58Vzq4fR1c+9GcO
  7zjpj8M7VbGTRqA0fdoq++cUF64AZX9mnWdRSZar9Qgw0jT4zeG4hGQpKX5/48oH
  VUyrKxNE3Ngf+ZKSfNQBNhhOsOQDJ7y4yXs//tipN6RUx6RIVoTEGnKLw6GkJuk1
  me0XDdECggEBAJy8NkWf90jhkuzAjNVVLh3hQlg1rxDYhHRy5NDc6HGlbrAykj5h
  Pvap27MBCRVm5eKDxMnWHwgeZep3lQCC1p/sUTQKazO1i4ArhYP4EDYM9FOd7Gd/
  bV2ZJZ1Y2YpJu9iS/g/UV9lAQ9/gEGje70T/Ze/l5h4ynKMAP8//mNJtt0Pnm+jA
  6G7ftvThPOS6jhPQwQbteZkYXDFDrIY0nnLU+XCPSkBYfCx9Uq2Zr7eJAP71Eu1k
  zM15IL3l0sREFIhnKLNLiSAIjE7EcYdvdCHdGJqYokK03ARtb4rE4k+46FpbbUgV
  ylQjpt3xCx/b46Thnqh8fxz3NhY+ZzGkMxcCggEBAIPNysl+ZdyB/qrAD54HfhUv
  K+hhG0x4mJmRvPyderL2lRwysqI3NerbmfiGS+dXHEivHKr8cLCd43LP+itaWTJP
  BfYPVGWvHm2ABEQ1+9hmDR0QgxupziJ7lSBnIjbepGcKMWKP0BmzQtJYlmwJmcWn
  5932uWIDZy3aRByBE4qjhyMoqwGe+Fo6S8Si3h2v00M7qh87bEmw0kY8M1w/eXQo
  d8C5i2TpXSmDbNu12wooGIcgoQvLDtT/WqmwzzVpp6rSSdAAAXaoaS6vyGy/+qYj
  h0gusT2s6RfToPe2vK6/uh5xs8A+xKrg8+aUnFwq7Kt40XRAHmYl3kjGHhDUkK8=
  -----END RSA PRIVATE KEY-----


PUBLIC_KEY: |
  -----BEGIN PUBLIC KEY-----
  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAt+1ueXtNusxvaqgxRRRb
  NMyXFjPxI+zG6jyRW1CsBH0ZW1EijvoIx5eA/Noi8tdwiRFBkcPfhXHvZdaidYTw
  fWOtfUzIl+Sg/7BM1sQ9+YfqMhk312D8lC/rLrPmrOQWVpWYz+z1B6bKfG1ZkAvk
  go0c3I5SichyPYSM1Tl0onXEpbL4giHO5hok4VvPMQb2EfSq8UD+mxI2zTHFAP1P
  tOQcTWdeKC5k+ddfOEAAJayh3tEWuW2nMj2wunk7pVxnYparZFPw6vMNSiQ8rs2x
  mYnZQhuqZJgMRW/SxbDn/Zl6P1mBjKPNyVoAbu+/Fx41De66cnNXMdjC2LpQ+xrR
  WpFjoMJEU4KDq37/Ewk4Ee2gBKnyuX23CZbZ/hPiSXczBD8fUJTdzHQUUHJB8YCC
  AZJnwvhA8Kf+cwI5vjxlVJeMguFqkXK53Cycxn6TXDEju5KiRTkyfAMwYpLnrUGi
  3zBO3mFClVA2EBaYTQf09WpKjg7DO0+08FH6FTRQHKimWBnTXb2RSme5YAmanY5C
  giX9Qmn9DwulbUlSB5VujxqESgy1cDTNd7xMEcwWthMIcIojfsfDmuKT41nU6aGO
  I8lQN6CTEFZIbzKy6WDthiKLLogxLJxB7TTbpq7a0SNRKNv+l8Qpogjd24OKvCCY
  xWwbB9FRoYZpa/Q9n3DRpMUCAwEAAQ==
  -----END PUBLIC KEY-----

